newTask_314676
nickkolok/chas-ege pull request #1043
Opened 2023-04-07 10:04 UTC by SugarHedgehog

2024-02-13 01:48 UTC, nickkolok requested changes

2024-02-13 01:48 UTC, nickkolok commented on zdn/mathoge/314676.js
> +    }
Это надо переписать покороче

2024-02-13 01:48 UTC, nickkolok commented on zdn/mathoge/314676.js
> +    function interval(f, x0) {
`f` перекрывается с именем функции ниже.  Не надо так!

2024-02-13 01:48 UTC, nickkolok commented on zdn/mathoge/314676.js
> +        if (f ^ a < 0)
Это правда побитовое XOR ?

2024-02-13 01:48 UTC, nickkolok commented on zdn/mathoge/314676.js
> +    genAssert(y0.isZ());
А почему ассерты в противоположном порядке?

2024-02-13 01:48 UTC, nickkolok commented on zdn/mathoge/314676.js
> +    console.log(answers);
Убрать)

2024-02-13 01:48 UTC, nickkolok commented on zdn/mathoge/314676.js
> +    chas2.task.modifiers.addCanvasIllustration({
Зоопарк

2025-02-04 13:38 UTC, nickkolok commented
@SugarHedgehog выглядит перспективно! Если допилить.

2025-02-06 18:42 UTC, nickkolok commented
Выглядит ещё более восхитительно!

Но, пожалуй, стОит ещё добавить в решение саму формулу  графика функции в двух видах: каноничный трёхчлен и трёхчлен с выделенным квадратом.

2025-02-06 18:43 UTC, nickkolok commented on zdn/mathoge/314676.js
> +    genAssert(points.length > 3, 'Количество целых точек меньше трёх');
А зачем нам три целых точки? Разве в этих задачах надо полностью восстанавливать функцию?

2025-02-06 18:51 UTC, nickkolok commented
И, конечно, этот файл нужно положить в отдельную папочку.

2025-02-07 12:07 UTC, SugarHedgehog commented on zdn/mathoge/314676.js
> +    genAssert(points.length > 3, 'Количество целых точек меньше трёх');
Рисунок не миленький

2025-02-07 12:08 UTC, SugarHedgehog commented
Жмякайте на resolve!
Ну невозможно так работать

2025-02-07 12:13 UTC, SugarHedgehog commented
> квадратом



> трёхчлен с выделенным квадратом.

зачем?

2025-02-07 13:04 UTC, nickkolok commented
> > трёхчлен с выделенным квадратом.
> 
> зачем?

Для облегчения проверки?

2025-02-07 13:05 UTC, nickkolok commented on zdn/mathoge/314676.js
> +    genAssert(points.length > 3, 'Количество целых точек меньше трёх');
А в обзаде/РешуЕГЭ только миленькие или немиленькие тоже есть?

2025-02-08 09:54 UTC, SugarHedgehog commented
> Для облегчения проверки?

Не понимаю, как это облегчает проверку.
Тогда уж писать: вершина находится там то, возрастает там, убивает там, наибольшее вооон там

2025-06-23 12:18 UTC, nickkolok commented on zdn/matoge2024/11/314676.js
> +        else
А слово `else` здесь вообще нужно?..

2025-06-23 12:21 UTC, nickkolok commented
А в остальном вроде всё ок.

2025-08-10 19:52 UTC, merged