newTask_99585
nickkolok/chas-ege pull request #1073
Opened 2023-06-20 10:30 UTC by SugarHedgehog

2023-07-15 00:09 UTC, nickkolok commented
Предлагается всё-таки перетащить классы прогрессий в отдельный файл. И закоммитить его отдельным пуллреквестом. @SugarHedgehog , получится?

2024-02-11 04:19 UTC, nickkolok commented
Тема актуальна.

2024-02-11 05:34 UTC, SugarHedgehog commented
> Предлагается всё-таки перетащить классы прогрессий в отдельный файл. И закоммитить его отдельным пуллреквестом. @SugarHedgehog , получится?

https://github.com/nickkolok/chas-ege/pull/1243
Классы уже приняты

2024-02-12 22:30 UTC, nickkolok requested changes

2024-02-12 22:30 UTC, nickkolok commented on zdn/matege2023p/9/99585.js
> +﻿let a = sluchch(2, 10);
Нужно бы обернуть в замыкание

2024-02-12 22:30 UTC, nickkolok commented on zdn/matege2023p/9/99585.js
> +var arr = ['Лена', 'Ира', 'Настя', 'Маша', 'Катя', 'Вера', 'Саша', 'Оля', 'Даша', 'Тоня', 'Аня', 'Ира', 'Женя'];
`.iz()` же!

2024-04-03 16:44 UTC, Kalendar2 commented
https://github.com/nickkolok/chas-ege/pull/1533

2025-02-15 14:28 UTC, closed without merging

2025-02-15 14:28 UTC, SugarHedgehog commented
https://github.com/nickkolok/chas-ege/commit/0481d05d49d4f6df3eb48cae0976a94071abc092