newTask_27118
nickkolok/chas-ege pull request #1091
Opened 2023-07-09 13:25 UTC by SugarHedgehog

2023-07-14 23:53 UTC, nickkolok commented
![image](https://github.com/nickkolok/chas-ege/assets/5008131/0070228e-544f-48c8-b8f6-b264708770d0)
Ручки зачётные :з

2023-07-15 00:00 UTC, nickkolok commented
Вычисления вроде ОК. Но как насчёт уже/ниже?

2023-07-15 00:06 UTC, nickkolok requested changes

2023-07-15 00:06 UTC, nickkolok commented on zdn/matege2023p/2/27118.js
> +		let ratioRadius = slKrome(ratioHight, 2, 10, 0.5);
Почему кроме-то?

2023-07-15 00:06 UTC, nickkolok commented on zdn/matege2023p/2/27118.js
> +		genAssert((answ * 1000).isZ());
`genAssert1000Z` или что-то такое есть. И комментарий к ошибке. Да, даже на уровне "Ответ слишком нецелый".

2023-07-15 00:06 UTC, nickkolok commented on zdn/matege2023p/2/27118.js
> +			ctx.fillStyle = "#61DC9A";
А это тут как, где и куда?..

2023-07-15 00:06 UTC, nickkolok commented on zdn/matege2023p/2/27118.js
> +			ctx.ellipse(100 + a, height / 2, (height - a) * 0.5, b, Math.PI / 2, Math.PI, 2 * Math.PI);
Где-то делится на 2, где-то умножается на 0.5...

2023-07-15 00:06 UTC, nickkolok commented on zdn/matege2023p/2/27118.js
> +		chas2.task.modifiers.addCanvasIllustration({
Унифицировать

2023-07-15 00:06 UTC, nickkolok commented on zdn/matege2023p/2/27118.js
> +		NAinfo.requireApiVersion(0, 2);
Эта штука, кажется, вообще в начале пишется...

2023-07-15 00:06 UTC, nickkolok commented on zdn/matege2023p/2/27118.js
> +		NAinfo.requireApiVersion(0, 2);
И нет, я не могу лихо объяснить, зачем оно надо. Вроде как чтобы знать, на какую версию тренажёра какой шаблон рассчитан...

2023-08-25 13:07 UTC, SugarHedgehog commented on zdn/matege2023p/2/27118.js
> +		let ratioRadius = slKrome(ratioHight, 2, 10, 0.5);
Потому что нахождение искомой величины слишком сильно упрощается

2023-08-25 13:42 UTC, nickkolok requested changes

2023-08-25 13:42 UTC, nickkolok commented on zdn/matege2023p/2/27118.js
> +		let ratioHight = sl(2, 10, 0.5);
Оно `Height` =/

2023-08-25 13:42 UTC, nickkolok commented on zdn/matege2023p/2/27118.js
> +			ctx.beginPath();
Я вот смотрю на это и понимаю, что нам таки нужна функция `drawEllipse()`, которая бы умещала эти 4 строки в одну... если этой функции ещё нет в стандартной библиотеке

2023-08-25 13:43 UTC, SugarHedgehog commented on zdn/matege2023p/2/27118.js
> +			ctx.beginPath();
Для чего она нужна?

2023-08-25 13:52 UTC, nickkolok commented on zdn/matege2023p/2/27118.js
> +			ctx.beginPath();
Чтобы рисовать эллипс одной строкой. Очень улучшает читаемость шаблона.

2023-08-25 13:53 UTC, SugarHedgehog commented on zdn/matege2023p/2/27118.js
> +			ctx.beginPath();
Не вижу смысла укорачивать и без того хорошую встроенную функцию

2023-08-25 13:55 UTC, SugarHedgehog commented on zdn/matege2023p/2/27118.js
> +			ctx.beginPath();
Рисовало бы оно весь цилиндр разом
Тогда был бы смысл

2023-08-25 14:01 UTC, nickkolok commented on zdn/matege2023p/2/27118.js
> +			ctx.beginPath();
Смысл есть даже так.

Одна строка вместо четырёх. Строка, обозначающая цельное действие. Потому что встроенные функции - они для сложных контуров, содержащих дуги эллипса, и только сбивают с толку.

2023-08-25 16:33 UTC, nickkolok approved these changes

2023-08-25 17:18 UTC, merged