Refactoring cube
nickkolok/chas-ege pull request #1095
Opened 2023-07-09 13:29 UTC by SugarHedgehog

2023-07-14 22:17 UTC, nickkolok requested changes
Я умудрился черрипикнуть `3.js` (не заметил потребностей в унификации).

2023-07-14 22:17 UTC, nickkolok commented on zdn/mat2014/B10/4.js
> +			ct.parallelepiped({
Теперь это называется иначе

2023-07-14 22:17 UTC, nickkolok commented on zdn/mat2014/B10/9.js
> +		NAtask.setTask({
Унифицировать

2023-07-14 22:17 UTC, nickkolok commented on zdn/mat2014/B10/3.js
> +		chas2.task.modifiers.addCanvasIllustration({
Унифицировать

2023-07-14 22:25 UTC, nickkolok commented
И `9.js` тоже, он считает правильно.
Но унифицировать всё равно надо.

2023-08-25 12:58 UTC, nickkolok commented on zdn/mat2014/B10/9.js
>  				strokeStyle: "#809DF2",
Цвета-константы

2023-08-25 12:59 UTC, nickkolok commented on zdn/mat2014/B10/9.js
> +			text: (v0 ? 'Диагональ' : 'Объём') + ' куба рав' + (v0 ? 'на' : 'ен') + ' $' + (v0 ? a : 3 * a * a * a).ts() +
Это точно та же самая задача? Очень серьёзно изменились и код, и формулировка задания...

2023-08-25 12:59 UTC, nickkolok commented on zdn/mat2014/B10/9.js
> -			text: (v0 ? 'Диагональ' : 'Объём') + ' куба рав' + (v0 ? 'на' : 'ен') + ' $' + (v0 ? a : 3 * a * a * a).ts() +
А-а, тот коммит откатывает этот...

2023-08-25 13:03 UTC, SugarHedgehog commented on zdn/mat2014/B10/9.js
> -			text: (v0 ? 'Диагональ' : 'Объём') + ' куба рав' + (v0 ? 'на' : 'ен') + ' $' + (v0 ? a : 3 * a * a * a).ts() +
Да
Я редкостно накосячила при копировании

2023-08-25 13:30 UTC, nickkolok commented
Сей нечаяннозачатый франкенштейн распилен на #1158 #1159 #1160
А частично и вовсе влит в `devel`

2023-08-25 13:30 UTC, closed without merging