function drawTetrahedron
nickkolok/chas-ege pull request #1099
Opened 2023-07-09 13:34 UTC by SugarHedgehog

2023-07-14 21:38 UTC, nickkolok requested changes

2023-07-14 21:38 UTC, nickkolok commented on lib/canvas.js
> +		[0, o.side, o.side * (o.angle).cos(), o.side * (o.angle).sin()], //1
Скобки

2023-07-14 21:38 UTC, nickkolok commented on lib/canvas.js
> +		this.drawLine(o.side * (30).cos(), o.side * (30).sin() / 2, o.side * (30).cos(), -(6).sqrt() * o.side * (30).sin() /
Вот вокруг числа скобки - не лишние. Но это... это ведь не градусы же!

2023-08-02 11:22 UTC, SugarHedgehog commented on lib/canvas.js
> +		this.drawLine(o.side * (30).cos(), o.side * (30).sin() / 2, o.side * (30).cos(), -(6).sqrt() * o.side * (30).sin() /
Работает - не трожь

2024-06-29 10:30 UTC, SugarHedgehog commented
Заменено классом и общей функцией отрисовки

2024-06-29 10:30 UTC, closed without merging