NewTask_621772
nickkolok/chas-ege pull request #1124
Opened 2023-08-03 14:27 UTC by SugarHedgehog

2023-09-08 20:02 UTC, nickkolok commented
Ай как нехорошо оно округляет!
![image](https://github.com/nickkolok/chas-ege/assets/5008131/0058b477-0675-4d5b-aafb-cb43afc6bbac)

Есть предложение вообще поставить ассерт, что ответ не менее 0.001

2023-09-08 20:04 UTC, nickkolok commented on zdn/matege2023p/4/621772.js
> +	function declensionOfAdjectives(number, adjective) {
Смотрится как заявка на отдельную функцию!

2023-09-08 20:04 UTC, nickkolok commented on zdn/matege2023p/4/621772.js
> +	function combination(k, n) {
А это точно надо вынести в функцию binomCoeff

2023-09-08 20:05 UTC, nickkolok commented on zdn/matege2023p/4/621772.js
> +		let color = ['аквамариновый', 'гранатовый', 'бежевый', 'бирюзовый',
В `om.trickyColors`

2023-10-18 18:15 UTC, SugarHedgehog commented on zdn/matege2023p/4/621772.js
> +		let color = ['аквамариновый', 'гранатовый', 'бежевый', 'бирюзовый',
https://github.com/nickkolok/chas-ege/pull/1250

2023-10-18 18:24 UTC, SugarHedgehog commented on zdn/matege2023p/4/621772.js
> +	function declensionOfAdjectives(number, adjective) {
https://github.com/nickkolok/chas-ege/pull/1251

2024-02-11 03:42 UTC, nickkolok requested changes

2024-02-11 03:42 UTC, nickkolok commented on zdn/matege2023p/4/621772.js
> +	function combination(k, n) {
В `mathjs`, по идее, должна быть готовая!

2024-11-30 15:08 UTC, merged