NewTask_27764
nickkolok/chas-ege pull request #1128
Opened 2023-08-03 14:31 UTC by SugarHedgehog

2023-09-08 21:09 UTC, nickkolok commented
Рисунок очень красивый :)

2023-09-08 21:13 UTC, nickkolok commented
А вот метки углов, как и метки отрезков - это должны быть отдельные осмысленные функции. Нам этой планиметрии предстоит ещё хз сколько и хз где - в том же ОГЭ. Так что начнём с простого - функция получает на вход координаты концов двух отрезков, желаемое расстояние от точки их пересечения и (опционально) толщину линии (??). Рисует дуги в углу со стороны первого конца первого отрезка и первого конца второго отрезка.

2023-09-18 16:12 UTC, SugarHedgehog commented
Зависит от https://github.com/nickkolok/chas-ege/pull/1202

2024-02-11 18:35 UTC, nickkolok commented on zdn/matege2023p/1/27764.js
> +			let vertex = coordinatesByAngle(10, 370, angle, 400);
Там, кажется, была функция, которая рисует отрезок из точки под углом?..

2024-02-11 18:36 UTC, nickkolok commented on zdn/matege2023p/1/27764.js
> +			ctx.drawLineAtAngle(10, 370, angle / 2, 345);
Вот она)

2024-02-11 18:44 UTC, nickkolok commented
К тому, как считает, замечаний нет. Если есть ответы на вопросы к коду, выполняющему рисунок - можно принимать.

2024-02-12 14:10 UTC, nickkolok commented
Ждём #1378

2024-02-13 13:43 UTC, nickkolok requested changes

2024-02-13 13:43 UTC, nickkolok commented on zdn/matege2023p/1/27764.js
> +			let vertex = ctx.drawLineAtAngle(10, 370, angle, 400);
CQ проводится два раза, причём вот тут - чёрным.
![image](https://github.com/nickkolok/chas-ege/assets/5008131/6f254613-d0ec-438f-90db-19040025551e)

2024-02-15 22:02 UTC, merged