NewTask 3353
nickkolok/chas-ege pull request #1134
Opened 2023-08-04 08:01 UTC by SugarHedgehog

2024-02-13 00:55 UTC, nickkolok requested changes
![image](https://github.com/nickkolok/chas-ege/assets/5008131/57d62a33-c96a-4836-94c2-1e20214aab6b)

Цвет. Нужны ли штрыпки на сторонах ромба? И почему стоит метка "пар-гр-м", если это ромб?

2024-02-13 00:55 UTC, nickkolok commented on zdn/matege2023p/1/3353.js
> +			text: 'В ромбе $' + copyVertices.permuteCyclic(sl(1, 3)).join('') + '$ угол $' + subangle.join('') +
А чего не от нуля? Вершины вот прям обязательно надо перемешать хоть чуть-чуть?

2024-02-13 00:55 UTC, nickkolok commented on zdn/matege2023p/1/3353.js
> +		let vertices = [];
ыть!!

2024-02-17 20:59 UTC, nickkolok requested changes

2024-02-17 20:59 UTC, nickkolok commented on zdn/matege2023p/1/3353.js
> +s
Ыыы?

2024-02-17 20:59 UTC, nickkolok commented on zdn/matege2023p/1/3353.js
> +		let angle = sl(91, 179);
А чего  не от единицы?

2024-02-18 16:05 UTC, nickkolok commented on zdn/matege2023p/1/3353.js
> +		let angle = sl(91, 179);
Вопрос в силе. Что мешает?

2024-02-20 17:18 UTC, SugarHedgehog commented on zdn/matege2023p/1/3353.js
> +		let angle = sl(91, 179);
1) Потому что рисунок перестаёт соответсовать условию
2) Если менять спрашиваемый угол - то меняется ВООБЩЕ ВСЁ

2024-02-20 17:36 UTC, merged