NewTask 3354
nickkolok/chas-ege pull request #1135
Opened 2023-08-04 08:01 UTC by SugarHedgehog

2024-02-11 03:46 UTC, nickkolok requested changes

2024-02-11 03:46 UTC, nickkolok commented on zdn/matege2023p/1/3354.js
> +		let vertices = [];
`let vertices = om.latbukv.iz(4)` или как-то так?..

2024-02-11 21:46 UTC, nickkolok requested changes

2024-02-11 21:46 UTC, nickkolok commented on zdn/matege2023p/1/3354.js
> +			letters = letters.reverse();
Это даже в этом шаблоне встречается дважды, чего там о других говорить! Нам срочно нужны `Array.prototype.rndReverse()` и `String.prototype.rndReverse()` !

2024-02-11 21:46 UTC, nickkolok commented on zdn/matege2023p/1/3354.js
> +		let vertices = om.latbukv.iz(4)
`variativeABC()` *робко*

2024-02-18 17:07 UTC, nickkolok commented on zdn/matege2023p/1/3354.js
> +			letters = letters.reverse();
Бамп

2024-02-20 17:39 UTC, SugarHedgehog commented
Поздравляю
Теперь этот шаблон покрыт 3353
Этот нафиг не нужен

2024-02-20 18:30 UTC, nickkolok commented
Если не нужен  - так, может, и закрыть?..

2024-02-28 17:42 UTC, SugarHedgehog commented
https://github.com/nickkolok/chas-ege/pull/1134
Перекрыто

2024-02-28 17:43 UTC, SugarHedgehog commented
https://github.com/nickkolok/chas-ege/pull/1134
Перекрыто

2024-02-28 17:43 UTC, closed without merging