newTask_27758
nickkolok/chas-ege pull request #1138
Opened 2023-08-11 06:13 UTC by SugarHedgehog

2024-02-13 00:00 UTC, nickkolok commented
Цвета. Пробел после точки. Функции для дуг и штрихов.
![image](https://github.com/nickkolok/chas-ege/assets/5008131/589ae317-03a7-426d-a0df-5e9840bbaab0)

2024-02-13 00:02 UTC, nickkolok requested changes
А считает правильно

2024-02-13 00:02 UTC, nickkolok commented on zdn/matege2023p/1/27758.js
> +		let vertices = [];
ыть

2024-02-13 00:02 UTC, nickkolok commented on zdn/matege2023p/1/27758.js
> +			//ctx.arc(390, 370, 45, -0.85 * Math.PI, -0.72 * Math.PI);
А это что? О_О

2024-02-18 12:32 UTC, nickkolok commented on zdn/matege2023p/1/27758.js
> +			ctx.drawArc(10, 370, 40, 0, -0.5 * Math.PI / 2.8, true);
А почему не `drawArcBetweenSegments` ?

2024-02-18 12:32 UTC, SugarHedgehog commented on zdn/matege2023p/1/27758.js
> +			ctx.drawArc(10, 370, 40, 0, -0.5 * Math.PI / 2.8, true);
Потому что угол и так известен

2024-02-18 12:44 UTC, merged