newTask_119&121
nickkolok/chas-ege pull request #1142
Opened 2023-08-11 06:17 UTC by SugarHedgehog

2024-02-12 23:12 UTC, nickkolok commented
Объединяем с #1143 ? Тут ведь даже формула та же, только вычисления в другую сторону!

2024-02-12 23:14 UTC, nickkolok requested changes
Короче, настаиваю на объединении. Формула одна, всё одинаковое, разница только что дано / что спрашивают.

2024-02-12 23:14 UTC, nickkolok commented on zdn/matege2023p/1/119.js
> +	do {
тут понятно

2024-02-12 23:14 UTC, nickkolok commented on zdn/matege2023p/1/119.js
> +	if (sl1())
Вот он, `.rndReverse()`, да?

2024-02-12 23:14 UTC, nickkolok commented on zdn/matege2023p/1/119.js
> +		ctx.arc(200, 200, 180, 0, 2 * Math.PI);
`drawArc()`. Или даже `drawEllipse()`. Кто лаконичнее?

2024-02-12 23:14 UTC, nickkolok commented on zdn/matege2023p/1/119.js
> +		text: 'Отрезки $' + vertices.slice(0, 2).shuffle().join('') + '$ и $' + vertices.slice(2, 4).shuffle()
Диаметры перечислять в случайном порядке

2024-02-18 14:09 UTC, SugarHedgehog commented
> Объединяем с #1143 ? Тут ведь даже формула та же, только вычисления в другую сторону!

Автор запутается с буковками и всё сломает

2024-02-18 14:32 UTC, nickkolok requested changes

2024-02-18 14:32 UTC, nickkolok commented on zdn/matege2023p/1/119.js
> +	if (sl1())
Замечание в силе

2024-02-20 17:35 UTC, SugarHedgehog commented on zdn/matege2023p/1/119.js
> +	if (sl1())
НЕТ
ЭТО ДРУГОЕ

2024-02-20 17:41 UTC, SugarHedgehog commented on zdn/matege2023p/1/119.js
> +	if (sl1())
Не ломай шаблон

2024-02-20 18:25 UTC, merged