newTask_153
nickkolok/chas-ege pull request #1145
Opened 2023-08-11 06:18 UTC by SugarHedgehog

2024-02-11 03:48 UTC, nickkolok requested changes

2024-02-11 03:48 UTC, nickkolok commented on zdn/matege2023p/1/153.js
> +		let vertices = [];
`om.latbukv.iz(4)` ?

2024-02-11 03:48 UTC, nickkolok commented on zdn/matege2023p/1/153.js
> +			ctx.arc(180, 200, 150, 0, 2 * Math.PI);
drawArc

2024-02-11 03:48 UTC, nickkolok commented on zdn/matege2023p/1/153.js
> +				'Найдите четвёртую сторону четырёхугольника.',
Так в ФИПИ  и было, без буковок?

2024-02-11 20:45 UTC, nickkolok commented on zdn/matege2023p/1/153.js
> +				'Найдите четвёртую сторону четырёхугольника.',
В ФИПИ так и написано - "четвёртую сторону"?

2024-02-11 21:21 UTC, nickkolok commented on zdn/matege2023p/1/153.js
> +				'Найдите четвёртую сторону четырёхугольника.',
Погуглил. За ФИПИ не ручаюсь, но такая формулировка определённо бывает. Имеет ли смысл делать вариативность на указание стороны буковками?

2024-02-11 21:24 UTC, nickkolok commented on zdn/matege2023p/1/153.js
> +		let vertices = window.latbukv.iz(4);
А зачем мы делаем вот это, когда есть `variativeABC()` ?

2024-02-11 21:25 UTC, nickkolok commented
После ответов на вопросы можно и смёржить...

2024-02-12 19:34 UTC, SugarHedgehog commented on zdn/matege2023p/1/153.js
> +				'Найдите четвёртую сторону четырёхугольника.',
Слишком проблематично встроить

2024-02-12 20:07 UTC, merged