newTask_27592
nickkolok/chas-ege pull request #1148
Opened 2023-08-11 06:22 UTC by SugarHedgehog

2023-08-23 15:12 UTC, nickkolok commented on zdn/matege2023p/1/27592.js
> +		let vertices = [];
`om.latbukv.iz(5)` ?

2023-08-23 15:14 UTC, nickkolok commented on zdn/matege2023p/1/27592.js
> +			question.data = question.data.reverse();
Так тут можно не только переворачивать, но и по кругу тасовать. Кажется, как раз недавно была очень удачно написана соответствующая функция...

2023-08-23 15:15 UTC, nickkolok commented on zdn/matege2023p/1/27592.js
> +					sl(1, 3)).join('') + '' + '$.',
Здесь пустую строку можно не прибавлять.

2023-08-23 15:58 UTC, nickkolok commented
Штрыпочки надо бы поцентрее. Я дрпускаю смещение штрыпки относительно центра отрезка (если там визуально эстетичнее так), но смещение центра штрыпки относительно отрезка - это не очень.
Может, и правда функцию?..

![image](https://github.com/nickkolok/chas-ege/assets/5008131/62aea5c7-a637-4a20-8d5c-40737b94efe4)

2023-09-04 13:49 UTC, SugarHedgehog commented on zdn/matege2023p/1/27592.js
> +			question.data = question.data.reverse();
Это действительное делается ниже!

2023-09-08 19:22 UTC, nickkolok commented on zdn/matege2023p/1/27592.js
> +					sl(1, 3)).join('') + '' + '$.',
... а если её можно не прибавлять - то не нужно её прибавлять :)

2024-02-11 02:46 UTC, nickkolok requested changes

2024-02-11 02:46 UTC, nickkolok commented on zdn/matege2023p/1/27592.js
> +			ctx.strokeInMiddleOfSegment(390+5, 350+5, 255, 200, 10);
Не-не-не, для двойной штрыпочки д.б. отдельная функция! Причём расстояние между штрыпочками можно рассчитывать исходя из толщины штрыпочки. Например, удвоенной.

2024-02-11 02:47 UTC, nickkolok commented on zdn/matege2023p/1/27592.js
> +			ctx.strokeInMiddleOfSegment(390+5, 350+5, 255, 200, 10);
Например, можно `ctx.strokeInMiddleOfSegment(390+5, 350+5, 255, 200, 10, 2);`

Зачем это надо? А затем, что однажды ФИПИ  **внезапно** выложит 20 новых задач по планиметрии, и их нужно будет быстро, решительно закодить!

2024-02-20 17:36 UTC, SugarHedgehog commented on zdn/matege2023p/1/27592.js
> +			ctx.strokeInMiddleOfSegment(390+5, 350+5, 255, 200, 10);
Я не буду писать этот бред

2024-02-20 18:34 UTC, nickkolok commented on zdn/matege2023p/1/27592.js
> +			ctx.strokeInMiddleOfSegment(390+5, 350+5, 255, 200, 10);
Нарисовать два штришочка на расстоянии, равно удвоенной толщине штришочка - это нетривиальная задача, которая предполагает тригонометрию.

Я настаиваю.

2024-02-29 01:10 UTC, nickkolok commented
Я набросал, потестить прошу самостоятельно.

```js
CanvasRenderingContext2D.prototype.strokeInMiddleOfSegment = function(x1, y1, x2, y2, length, quantity) {
	/** Ставит штрихи длины length на середине отрезка перпендикулярно ему*/
	quantity = quantity || 1;
	let middle = coordinatesMiddleOfSegment(x1, y1, x2, y2);
	let angle = ((y2 - y1) / (x2 - x1)).arctg();
	let thickness = this.lineWidth;
	let gap = this.lineWidth * 3;
	let initialBias = (quantity - 1) * (gap + thickness) / 2;
	for (let i = 0; i < quantity; i++) {
		let bias = initialBias - i * (gap + thickness);
		//alert(bias + " " + initialBias);
		this.drawLineAtAngle(middle[0] + bias * angle.cos(), middle[1] + bias * angle.sin(), angle + 0.5 * Math.PI, +length);
		this.drawLineAtAngle(middle[0] + bias * angle.cos(), middle[1] + bias * angle.sin(), angle + 0.5 * Math.PI, -length);
	}
};



(function() {
	retryWhileError(function() {
		NAinfo.requireApiVersion(0, 2);

		let a = sl(2, 100);

		let vertices = om.latbukv.iz(5);

		let question = {
			data: 0,
			find: 0,
			answ: 0,
		};
		switch (sl(1, 6)) {
		case 1:
			question.data = vertices.slice(0, 3);
			question.find = [vertices[0], vertices[3], vertices[4]];
			question.answ = a * 0.25;
			break;
		case 2:
			question.data = [vertices[0], vertices[3], vertices[4]];
			question.find = vertices.slice(0, 3);
			question.answ = a * 4;
			break;
		case 3:
			question.data = vertices.slice(0, 3);
			question.find = vertices.slice(1, 5);
			question.answ = a * 0.75;
			break;
		case 4:
			question.data = vertices.slice(1, 5);
			question.find = vertices.slice(0, 3);
			question.answ = a * 4 / 3;
			genAssertZ1000(question.answ, 'Кривой ответ');
			break;
		case 5:
			question.data = vertices.slice(1, 5);
			question.find = [vertices[0], vertices[3], vertices[4]];
			question.answ = a / 3;
			genAssertZ1000(question.answ, 'Кривой ответ');
			break;
		case 6:
			question.data = [vertices[0], vertices[3], vertices[4]];
			question.find = vertices.slice(1, 5);
			question.answ = a * 3;
			break;
		} //TODO: упростить

		let paint1 = function(ctx) {
			ctx.lineWidth = 2;

			ctx.drawLine(10, 350, 390, 350);
			ctx.drawLine(10, 350, 120, 50);

			ctx.drawLine(120, 50, 390, 350);

			ctx.drawLine(65, 200, 255, 200);

			//штрихи
			ctx.lineWidth = 1;
			ctx.strokeStyle = "red";
			
			// Играться тут!!!
			
			ctx.strokeInMiddleOfSegment(10, 350, 65, 200, 10, 3);
			
			
			
			ctx.strokeStyle = "black";
			ctx.strokeInMiddleOfSegment(10, 350, 65, 200, 10);
			ctx.strokeInMiddleOfSegment(120, 50, 65, 200, 10);

			ctx.strokeInMiddleOfSegment(120, 50, 255, 200, 10);
			ctx.strokeInMiddleOfSegment(120+5, 50+5, 255, 200, 10);

			ctx.strokeInMiddleOfSegment(390, 350, 255, 200, 10);
			ctx.strokeInMiddleOfSegment(390+5, 350+5, 255, 200, 10);
			
			ctx.font = "23px liberation_sans";
			ctx.fillText(vertices[0], 120, 40);
			ctx.fillText(vertices[1], 10 - 5, 370 + 10);
			ctx.fillText(vertices[2], 390 - 10, 370 + 10);
			ctx.fillText(vertices[3], 255 + 5, 200);
			ctx.fillText(vertices[4], 65 - 25, 200);

		};

		NAtask.setTask({
			text: 'Площадь ' + ['треугольника', 'трапеции'][question.data.length - 3] + ' $' +
				question.data.permuteCyclic(sl(1, 3)).join('') +
				'$ равна $' + a + '$, $' + vertices.slice(3, 5).shuffle().join('') +
				'$ – средняя линия, параллельная стороне $' +
				vertices.slice(1, 3).shuffle().join('') + '$. ' +
				'Найдите площадь ' + ['треугольника', 'трапеции'][question.find.length - 3] + ' $' + question.find.permuteCyclic(
					sl(1, 3)).join('') + '$.',
			answers: question.answ,
			analys: '',
		});
		NAtask.modifiers.addCanvasIllustration({
			width: 400,
			height: 400,
			paint: paint1,
		});
	}, 1000);
})();
```

2024-02-29 20:18 UTC, merged