joinWithConjunction
nickkolok/chas-ege pull request #1177
Opened 2023-08-30 09:59 UTC by SugarHedgehog

Соединяет массив естественным для задач способом

2023-08-30 14:52 UTC, nickkolok requested changes

2023-08-30 14:52 UTC, nickkolok commented on lib/array.js
> +	/** [a=5,b=1,c=9].joinWithConjunction() => "a=5, b=1 и c=9"*/
Кавычек в примере не хватает

2023-08-30 17:38 UTC, SugarHedgehog commented on lib/array.js
> +	return this.slice(0, this.length - 1).join(separator) +  ' и ' + this[this.length - 1];
Союз "а" оказался менее универсальным

2023-08-30 17:39 UTC, SugarHedgehog commented on lib/array.js
> +	return this.slice(0, this.length - 1).join(separator) +  ' и ' + this[this.length - 1];
К примеру, "сечение проходящее через вершины А, Б, а С"

2023-09-01 14:52 UTC, nickkolok commented
Выглядит разумным выделить функцию .joinLast(a,b)
Первый аргумент соединяет все, кроме последнего и предпоследнего, а второй - их.

Причём если аргумент всего один, то считается, что единственный аргумент соединяет последние, а остальные соединяются запятой.

А эту функцию уже сделать зависящей от той.

2023-09-01 14:53 UTC, nickkolok commented
И, если можно, расположить её после .soed()

2023-09-08 09:45 UTC, SugarHedgehog commented
```js
(function() {
	Array.prototype.joinLast = function(conjunctionForFirst, conjunctionForLast) {
		/**Если  conjunctionForFirst - 
		Соединяет массив запятыми и соединяет два последних элемента conjunctionForFirst */
		/**Если  conjunctionForFirst и conjunctionForLast - 
		Соединяет массив conjunctionForFirst и соединяет два последних элемента conjunctionForLast */
		if (conjunctionForLast != undefined) {
			return this.slice(0, this.length - 1).join(conjunctionForFirst) + conjunctionForLast + this[this.length - 1];
		} else {
			return this.slice(0, this.length - 1).join(', ') + conjunctionForFirst + this[this.length - 1];
		}

	};


	Array.prototype.joinWithConjunction = function(conjunction) {
		/** Соединяет массив запятыми и соединяет для последних элемента союзом conjunction*/
		/** ["a=5","b=1","c=9"].joinWithConjunction() => "a=5, b=1 и c=9"*/
		return this.joinLast(conjunction);
	};
	retryWhileError(function() {
		NAinfo.requireApiVersion(0, 2);
		let word = tovary.ie.iz(sl(3, 6));
		NAtask.setTask({
			text: word.joinWithConjunction(' и ') + '<br>' +
				word.joinLast(', не ', ', а ') + '<br>' +
				word.joinLast(', да ', ', но не ') + '<br>' +
				word.joinLast(', то ', ' или ') + '<br>' +
				word.joinLast(' и ', ' или '),
			answers: 0,
			analys: '',
		});
	});
})();

```

2023-09-08 10:17 UTC, nickkolok commented on lib/array.js
> +	} else {
Если быть совсем точным, то слово `else` тут формально лишнее... Понятно, почему?

2023-09-08 10:18 UTC, SugarHedgehog commented on lib/array.js
> +	} else {
Действительно!

2023-09-08 10:19 UTC, nickkolok requested changes

2023-09-08 10:19 UTC, nickkolok commented on lib/array.js
> -
А это зачем убирать?

2023-09-08 10:19 UTC, nickkolok commented on lib/array.js
> +Array.prototype.joinWithConjunction = function(conjunction) {
Так ведь по умолчанию через "и" должно соединять? Так, как сейчас, никакого смысла нет - просто ещё одно название для `joinLast()`. Есть предложение
```js
return this.joinLast(" и ");
```
и никаких аргументов :)

2023-09-08 10:44 UTC, SugarHedgehog commented on lib/array.js
> +Array.prototype.joinWithConjunction = function(conjunction) {
Тогда вообще нафиг joinWithConjunction, если joinLast всё и так может((

2023-09-08 10:47 UTC, SugarHedgehog commented on lib/array.js
> +Array.prototype.joinWithConjunction = function(conjunction) {
Только ради не отдачи функции аргументов?

2023-09-08 11:10 UTC, nickkolok commented on lib/array.js
> +Array.prototype.joinWithConjunction = function(conjunction) {
Чтобы раскладку в процессе не менять :-Р
Да и потом, выпиливать её теперь из кучи шаблонов уже утомительно. Пусть будет, я не возражаю.

2023-09-08 13:08 UTC, nickkolok approved these changes

2023-09-08 13:09 UTC, nickkolok commented
Вот вернул я на место ту строку, что кто-то случайно удалил - и теперь оно даёт смёржиться...

2023-09-08 13:10 UTC, merged