UpadeteDrawParallelepiped
nickkolok/chas-ege pull request #1179
Opened 2023-09-01 11:58 UTC by SugarHedgehog

Теперь можно рисовать сечения парллелепипеда через его вершины

Но можно запустить эту же функцию для любой фигуры

Теперь вершинки подписываются!

2023-09-03 19:47 UTC, nickkolok commented on lib/canvas.js
> +
ну вот что это?(

2023-09-03 19:50 UTC, nickkolok requested changes

2023-09-03 19:50 UTC, nickkolok commented on lib/canvas.js
> +		vertex.permuteCyclic(1);
Тут вот есть нюанс... Получается, что массив `vertex`, переданый по ссылке, изменяется. Он, конечно, в результате изменений возвращается в исходное состояние... или нет?
Чтобы не ломать голову, лучше просто вместо этого использовать `i` или `i+1`.

2023-09-03 19:50 UTC, nickkolok commented on lib/canvas.js
> +	this.fillStyle = fillStyle || om.transparentBrandColors.iz();
А на эту штуку (`om.transparentBrandColors`) пуллреквест есть?

2023-09-03 19:52 UTC, SugarHedgehog commented on lib/canvas.js
> +	this.fillStyle = fillStyle || om.transparentBrandColors.iz();
Есть
Так и называется

2023-09-03 20:33 UTC, nickkolok commented on lib/canvas.js
> +	this.fillStyle = fillStyle || om.transparentBrandColors.iz();
А можно без ребусов, просто номер?)

2023-09-04 12:53 UTC, SugarHedgehog commented on lib/canvas.js
> +	this.fillStyle = fillStyle || om.transparentBrandColors.iz();
https://github.com/nickkolok/chas-ege/pull/1181

2023-09-08 13:11 UTC, nickkolok requested changes
Замечания написаны по коду :)

2023-09-08 14:04 UTC, SugarHedgehog commented on lib/canvas.js
> +		vertex.permuteCyclic(1);
Массив возвращается в исходное положение

C i+1 фокус не получится
Тогда оно не сможет замкнуть фигуру

2023-09-08 14:05 UTC, SugarHedgehog commented on lib/canvas.js
> +
Ничего не знаю
vs code вообще не видит изменений в этом месте

2023-09-08 14:06 UTC, SugarHedgehog commented on lib/canvas.js
> +		vertex.permuteCyclic(1);
Либо придётся отдельным действием lineTo на начальную вершину
От чего я и хотела избавиться

2023-09-08 15:17 UTC, nickkolok commented on lib/canvas.js
> +		vertex.permuteCyclic(1);
Ох, искушает меня кое-кто поиграться...

2023-09-08 16:08 UTC, SugarHedgehog commented on lib/canvas.js
> +		vertex.permuteCyclic(1);
Прими и не трогай рабочее!

2023-09-08 16:27 UTC, nickkolok commented on lib/canvas.js
> +		vertex.permuteCyclic(1);
Я хорошо потрогал, проверил!

2023-09-08 16:47 UTC, nickkolok approved these changes

2023-09-08 16:47 UTC, merged