Line-intersect and arc
nickkolok/chas-ege pull request #1202
Opened 2023-09-17 16:35 UTC by SugarHedgehog

Немного функций для угла между отрезками

2023-09-19 00:09 UTC, nickkolok commented on lib/array_mt.js
> +	return Math.atan2(this[1].y - this[0].y, this[1].x - this[0].x);
Но... эта функция же теперь делает совсем другое! Она возвращаетне тангенс, она возвращает угол!

2023-09-19 00:10 UTC, nickkolok commented on lib/array_mt.js
> +Array.prototype.coordinatesOfIntersectionOfTwoSegments = function() {
Тогда уж начинать с префикса `mt_`

2023-09-19 00:14 UTC, nickkolok commented on lib/canvas.js
> +	let angle1 = XY1.mt_tgUnakl();
И вот тут загвоздка вылезает. Сделать тогда уж отдельную функцию типа `mt_tangentAngle`, а старую не трогать...

2023-09-19 00:20 UTC, nickkolok commented
Ввиду стратегической важности первый коммит - к которому нет претензий - черрипикнут в `devel`. Ребейзить не надо!

2023-12-14 22:51 UTC, nickkolok requested changes

2023-12-14 22:51 UTC, nickkolok commented on lib/canvas.js
> +	anticlockwise = anticlockwise || false;
А это не то же самое, что `!!anticlockwise` ?

2023-12-14 22:51 UTC, nickkolok commented on lib/array_mt.js
> +	return Math.atan2(this[1].y - this[0].y, this[1].x - this[0].x);
Эту штуку надо откатить!

2024-02-11 02:34 UTC, nickkolok requested changes

2024-02-11 02:34 UTC, nickkolok commented on zdn/matege2023p/1/27764.js
> +			ctx.arcBetweenSegmentsCount([vertex[0], vertex[1], 10, 370].concat(bisector1), 30, 2);
`Uncaught TypeError: ctx.arcBetweenSegmentsCount is not a function`

2024-02-11 02:34 UTC, nickkolok commented on lib/canvas.js
> +	anticlockwise = anticlockwise || false;
Этот вопрос таки тоже очень актуален!

2024-02-11 06:22 UTC, SugarHedgehog commented on lib/canvas.js
> +	anticlockwise = anticlockwise || false;
Не понимаю, к чему это
По умолчанию оборот по часовой
Если надо иначе, то пишем `true`

2024-02-11 14:16 UTC, nickkolok commented on lib/canvas.js
> +	anticlockwise = anticlockwise || false;
Мне кажется, что вместо
```js
anticlockwise = anticlockwise || false;
```
лучше писать
```js
anticlockwise = !!anticlockwise;
```
Но это не точно, могут быть возражения.

2024-02-11 16:39 UTC, nickkolok commented
Последний коммит черрипикнут как ba035cdc - поскольку всё равно корячиться с ребейзами и конфликтами.

2024-02-11 17:39 UTC, nickkolok commented
Отребейжено, можно смело закрывать
269db8ac366ee

2024-02-11 17:39 UTC, closed without merging