newTask_64485003
nickkolok/chas-ege pull request #1206
Opened 2023-09-19 14:48 UTC by SugarHedgehog

Ященко

2023-09-19 22:11 UTC, nickkolok commented on zdn/matege2024p/2/64485003.js
> +		let condition = (coeffs[0][0].texrndfrac(coeffs[0][1]) + '\\vec{' + letter[0] + '}\\cdot(');
Скобки лишние

2023-09-19 22:13 UTC, nickkolok commented on zdn/matege2024p/2/64485003.js
> +		condition += (coeffs[1][0].texrndfrac(coeffs[1][1]) + '\\vec{' + letter[1] + '}' + '+'.esli(coeffs[2][0] > 0) +
Зачем `+=`? Можно одной командой просто сложить

2023-09-19 22:13 UTC, nickkolok commented on zdn/matege2024p/2/64485003.js
> +			ctx.strokeStyle = om.secondaryBrandColors;
А это не массив?

2024-02-11 03:11 UTC, nickkolok requested changes

2024-02-11 03:11 UTC, nickkolok commented on zdn/matege2024p/2/64485003.js
> +		let condition = (coeffs[0][0].texrndfrac(coeffs[0][1]) + '\\vec{' + letter[0] + '}\\cdot(');
Форспуш форспушем, а замечания в силе

2025-03-30 21:27 UTC, nickkolok commented
Could get nothing but errors (iterations: 100000),
see console output for detailed stats.
First 16 error(s) are:

TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined
TypeError: om.smallLatinLetters is undefined

Detailed stats:

om.smallLatinLetters is undefined : 1530
undefined has no properties : 98470

2025-06-23 12:12 UTC, nickkolok commented
```tex
{1}\frac{1}{3}\vec{d}\cdot({3}\frac{1}{2}\vec{u}-\frac{2}{5}\vec{s})
```

```tex
\frac{1}{2}\vec{q}\cdot( 1 \vec{p}+ 1{,}6 \vec{w})
```

Можно, конечно, потрогать `.plusminus()` , чтобы переваривал пробелы. Но я боюсь, что в каком-то из прошлых шаблонов его действие уже когда-то нейтрализовывалось пробелами. Поэтому, вероятно, тут нужно стругать костылики-replace прямо в шаблоне.

2025-08-10 20:32 UTC, nickkolok commented on zdn/matege2024p/2/64485003.js
> +		let distAB = dist(midA, midB, 'Векторы A и B слиплись');
А комментарий точно передан в нужную функцию?

2025-08-14 15:41 UTC, nickkolok commented on zdn/matege2024p/2/64485003.js
> +		genAssert(distBC>3);
А тут и ещё раз ниже?

2025-08-15 22:23 UTC, nickkolok commented on zdn/matege2024p/2/64485003.js
> +		genAssert(!math.deepEqual(vectorA, vectorC), 'Вектора A и C совпадают');
А вектора В и С совпасть не могут?

2025-08-15 22:25 UTC, nickkolok commented on zdn/matege2024p/2/64485003.js
> +		let letter = window.smallLatinLetters.iz(3);
`om` ?

2025-09-15 22:05 UTC, nickkolok commented
<img width="1254" height="618" alt="изображение" src="https://github.com/user-attachments/assets/2dd25efe-c02a-41c4-bad8-0d3910b1f14c" />

Всё ещё вылезают единицы-множители. И да,

```
TypeError: can't access property "iz", om.smallLatinLetters is undefined
```
Но если убрать `om.` , то всё работает. Не знаю, как поступить в этом случае.

2025-09-16 07:01 UTC, SugarHedgehog commented
> om.smallLatinLetters

Потому что оно window.smallLatinLetters

2025-09-21 20:54 UTC, nickkolok commented
Выглядит так, что всё хорошо!

<img width="1238" height="624" alt="image" src="https://github.com/user-attachments/assets/ef0b2682-2e91-485e-943a-79f4b18b3de5" />

2025-09-21 20:56 UTC, merged