newTask_245171
nickkolok/chas-ege pull request #1229
Opened 2023-10-03 16:38 UTC by SugarHedgehog

2023-10-08 21:20 UTC, nickkolok requested changes

2023-10-08 21:20 UTC, nickkolok commented on zdn/matege2024p/7/245171.js
> +            expr: ['-'.esli(sl1()) + 'sqrt(' + sqrt2 + ')', 'sqrt(' + sqrt1 + ')' + ['sin', 'cos'].iz() + 'pow((' + frac[0] + 'pi)/(' + frac[1] + '),2)'].shuffle().slag().plusminus(),
А вот `plusminus()` здесь лишний :(
Он - древний костыль, сделанный тогда, когда CAS не было. В идеале нужно обходиться без него. Например, приписать каждому слагаемому случайный знак. Или сджойнить случайным знаком (`+` или `-`) и перед результатом поставить случайный знак (`-` или ничего). Вполне попахивает отдельной функцией под это дело.

2023-10-24 15:59 UTC, SugarHedgehog commented on zdn/matege2024p/7/245171.js
> +            expr: ['-'.esli(sl1()) + 'sqrt(' + sqrt2 + ')', 'sqrt(' + sqrt1 + ')' + ['sin', 'cos'].iz() + 'pow((' + frac[0] + 'pi)/(' + frac[1] + '),2)'].shuffle().slag().plusminus(),
https://github.com/nickkolok/chas-ege/pull/1261

2023-10-29 17:03 UTC, SugarHedgehog reviewed
Принимаем!

2023-10-29 17:04 UTC, merged