[new] [zdn] - newTask_99574
nickkolok/chas-ege pull request #1307
Opened 2023-12-05 19:27 UTC by SugarHedgehog

2023-12-12 22:51 UTC, nickkolok requested changes

2023-12-12 22:51 UTC, nickkolok commented on zdn/matege2024p/10/99574.js
> +	} while (!(answ * 100).isZ());
А чего не `genAssert`??

2023-12-12 22:51 UTC, nickkolok commented on zdn/matege2024p/10/99574.js
> +		['абрикос', 'курага'],
Где-то это я уже видел... Или нет?..

2023-12-13 09:40 UTC, SugarHedgehog commented on zdn/matege2024p/10/99574.js
> +	} while (!(answ * 100).isZ());
Это старющая разработка со второго курса
Взято прямиком из суйни

2023-12-13 09:41 UTC, SugarHedgehog commented on zdn/matege2024p/10/99574.js
> +		['абрикос', 'курага'],
https://github.com/nickkolok/chas-ege/issues/761

2023-12-14 19:46 UTC, merged