Задача 60 ФИПИ #1303
nickkolok/chas-ege pull request #1309
Opened 2023-12-08 18:48 UTC by Aisse-258

2023-12-09 10:40 UTC, SugarHedgehog commented
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/83b0fe00-6839-4e1f-b2ef-a029b21e25c3)
Вопросики к склонению

2023-12-11 20:18 UTC, Aisse-258 commented
@SugarHedgehog скорее к работе функции склонения единиц измерения
похоже что она не понимает дроби
Её нужно доработать, тогда шаблон будет работать правильно

2023-12-12 22:49 UTC, nickkolok requested changes

2023-12-12 22:49 UTC, nickkolok commented on zdn/matege2024p/10/99606.js
> +		let k = sl(1,10,0.01);//время1
То же, что и в #1310

2023-12-12 22:49 UTC, nickkolok commented on zdn/matege2024p/10/99606.js
> +				chislitlx(m, 'час').split(" ")[1]+' — со скоростью  $v_2='+v2.ts()+' \\dfrac{\\text{км}}{\\text{ч}}$. '+
Остроумно! И впрямь, с chislitlx и латехом у нас беда...
@SugarHedgehog, прошу открыть суйню на разработку более прогрессивной замены `chislitlx` - которая будет уметь вставлять "таких же" (или любой другой текст), оборачивать в латех и... чего там ещё не хватает? Параметры делать именованными.

2023-12-12 22:49 UTC, nickkolok commented on zdn/matege2024p/10/99606.js
> +				' ехал'+['','а','о','и'][transp.rod]+' со скоростью $v_0='+v0.ts()+' \\dfrac{\\text{км}}{\\text{ч}}$, '+
Алсо, после принятия #1302 можно использовать его - будет таки несколько более читаемо.

2023-12-15 16:00 UTC, Aisse-258 commented
перезалив в #1315

2023-12-15 16:00 UTC, closed without merging