Сделана задача №119979, обзад №119979, matege2016p/11/119979.js
nickkolok/chas-ege pull request #1318
Opened 2023-12-17 19:53 UTC by Kalendar2

2023-12-18 16:19 UTC, nickkolok commented
Поздравляю, @Kalendar2 , Вам удалось сделать свой первый пуллреквест! Прежде, чем он будет принят, по нему будут высказаны замечания и пожелания. Вы можете возражать, если считаете нужным, однако последнее слово остаётся за мной как за научным руководителем всего это <s>безобразия</s> проекта. Обсуждение можно вести как для пуллреквеста в целом (здесь), так и по отдельным его строкам. Видите ли Вы это сообщение, в том числе у себя на почте?

2023-12-18 16:22 UTC, nickkolok requested changes

2023-12-18 16:22 UTC, nickkolok commented on zdn/mat2014/B14/119979.js
> +				(((-1) * a * (x1 + x2)) / 2)) + plusmin('x^2+' + (a * x1 * x2 + c)) + 'x+' + d + ',' + '$$' +
Почти везде вместо `(-1) * a` можно писать `-a`, что существенно короче и более читаемо.

2023-12-18 16:22 UTC, nickkolok commented on zdn/mat2014/B14/119979.js
> +		analys: '$$' + 'Решение:' + '$$' + 'Найдём закон изменения скорости: ' + '$$' + 'v(t)=x^{\'}(t)=' + plusmin(a +
Решение не требуется начинать с отдельного заголовка. Несмотря на то, что оболочка отладки не ставит никакого заголовка перед решением, при генерации задач в других оболочках он вставится сам.

2024-01-15 12:46 UTC, Kalendar2 commented
Здравствуйте, Николай Николаевич. Сообщение увидел. Приступаю к исправлению кода.

>Понедельник, 18 декабря 2023, 19:20 +03:00 от nickkolok ***@***.***>:
>
>Поздравляю,  @Kalendar2 , Вам удалось сделать свой первый пуллреквест! Прежде, чем он будет принят, по нему будут высказаны замечания и пожелания. Вы можете возражать, если считаете нужным, однако последнее слово остаётся за мной как за научным руководителем всего это  безобразия проекта. Обсуждение можно вести как для пуллреквеста в целом (здесь), так и по отдельным его строкам. Видите ли Вы это сообщение, в том числе у себя на почте?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <nickkolok/chas-ege/pull/1318/c1860948490 @ github . com>

--
Сергей Алендарь
Отправлено из Почты  Mail.ru

2024-02-02 01:39 UTC, nickkolok requested changes

2024-02-02 01:39 UTC, nickkolok commented on zdn/mat2014/B14/119979.js
> +			'$$ x(t)=' + '\\frac{1}{' + b + '}' + plusmin('x^3+' + ((-a * (x1 + x2)) / 2)) + plusmin('x^2+' + (a * x1 * x2 + c)) + plusmin('x+' + d) + ',' +
Зачем  же складывать две строки-константы, если можно просто сделать из них одну?

2024-02-02 01:39 UTC, nickkolok commented on zdn/mat2014/B14/119979.js
> +		analys: '$$Решение:$$' + 'Найдём закон изменения скорости: ' +
А что я написал выше про заголовок решения?..

2024-02-02 01:40 UTC, nickkolok commented
А как у нас получилось вот это?..
![image](https://github.com/nickkolok/chas-ege/assets/5008131/a521cfbd-f9d2-479c-b0e7-2f109e49da79)

2024-02-02 01:41 UTC, nickkolok commented
И вот это...
![image](https://github.com/nickkolok/chas-ege/assets/5008131/4579039a-aa5e-46b9-8582-91c69435ad57)


Вы проверяйте, пожалуйста, потщательнее :)

2024-02-16 15:42 UTC, nickkolok commented
Код хорош, и единственное замечание - это то, что файлы лежат не там. Найдите эту задачу в каталоге РешуЕГЭ этого года, пожалуйста, и соответственным образом перенесите в папку, поправив `main.js` и добавив её в `fipi.js`.

2024-02-20 18:04 UTC, merged