Только натуральные числа в sluchch
nickkolok/chas-ege pull request #1331
Opened 2024-01-22 20:26 UTC by SugarHedgehog

Размерашается кинуть в меня наковальней

2024-01-22 20:27 UTC, SugarHedgehog commented
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/52992e89-ee50-4d7f-9d4a-c009f1950c2a)

2024-02-09 01:10 UTC, nickkolok requested changes

2024-02-09 01:10 UTC, nickkolok commented on lib/func.js
> +	if(!s||window.nNumber)
Называться оно должно по-другому, поподробнее. `sluchch.forceIntegers`, например. Да, ЕМНИП, у функций могут быть свойства, а чего б нет?

2024-02-11 01:12 UTC, nickkolok requested changes

2024-02-11 01:12 UTC, nickkolok commented on sh/pechmat.html
> +			<input type="checkbox" id="nNumber" data-chasstorage-id="pech-nNumber"/><label for="nNumber">
Тогда уж и тут не `nNumber`, а `forceIntegers`. И далее везде. К чему плодить лишние названия?

2024-02-11 15:37 UTC, SugarHedgehog commented on sh/pechmat.html
> +			<input type="checkbox" id="nNumber" data-chasstorage-id="pech-nNumber"/><label for="nNumber">
Логично

2024-02-11 16:23 UTC, nickkolok requested changes

2024-02-11 16:23 UTC, nickkolok commented on sh/pechmat.js
> +	sluchch.forceIntegers = (options.forceIntegers) ? true : false;
Выглядит как тавтология. `options.forceIntegers` - оно же уже или `true`, или `false`, зачем его с чем-то сравнивать?..

2024-02-11 16:37 UTC, SugarHedgehog commented on sh/pechmat.js
> +	sluchch.forceIntegers = (options.forceIntegers) ? true : false;
А как мне определить sluchch.forceIntegers иначе???

2024-02-11 17:55 UTC, nickkolok requested changes

2024-02-11 17:55 UTC, nickkolok commented on lib/func.js
> +	if(!s||sluchch.forceIntegers)
Внезапный вопрос!  А если там нужно чётное число? Может, кастовать это только если запрошенный шаг меньше 1?

2024-02-15 21:14 UTC, nickkolok commented on sh/pechmat.js
> +	sluchch.forceIntegers = (options.forceIntegers) ? true : false;
`sluchch.forceIntegers = options.forceIntegers`

2024-02-15 21:15 UTC, nickkolok requested changes

2024-02-15 21:15 UTC, nickkolok commented on sh/pechmat.html
> +				Натуральные числа
Тут очень желательно поподробнее написать, где именно числа натуральные. Например, "Генерировать преимущественно натуральные числа".

2024-02-18 15:44 UTC, merged