Задача 27984 РешуЕГЭ [close #1354]
nickkolok/chas-ege pull request #1393
Opened 2024-02-13 20:00 UTC by Aisse-258

![image](https://github.com/nickkolok/chas-ege/assets/50519492/0a2c3c22-da91-4bc0-a525-7a4bafea7aba)
![image](https://github.com/nickkolok/chas-ege/assets/50519492/92d8cc64-4088-4917-a5fe-515fb69bba83)
![image](https://github.com/nickkolok/chas-ege/assets/50519492/90573697-fb2a-4f35-9500-03f3466e3563)

2024-02-14 15:59 UTC, nickkolok commented
По оформлению:
![image](https://github.com/nickkolok/chas-ege/assets/5008131/77e67b85-37c6-403d-8abb-206c55a4debe)

"горизонтана" - это не наречие, пишется раздельно.

"км" можно не включать в формулу, чтобы не очень выделялось. Всё-таки оно не в дроби, и дробей здесь нет.

2024-02-14 16:02 UTC, nickkolok commented
Далее, есть некая непонятность на тему того, что `main.js` подправлен в наборе 2023-го года, а сам файл лежит в 2024-м.

2024-02-14 16:09 UTC, nickkolok requested changes

2024-02-14 16:09 UTC, nickkolok commented on zdn/matege2024p/9/27984.js
> +		NAtask.modifiers.allDecimalsToStandard();
А они тут бывают? Даже если и бывают - то тут латех, надо передавать `true`, чтобы запятая стояла красиво.

2024-02-18 20:04 UTC, Aisse-258 commented
> Далее, есть некая непонятность на тему того, что `main.js` подправлен в наборе 2023-го года, а сам файл лежит в 2024-м.

там симлинк

2024-02-20 17:21 UTC, merged