Newtask deriv 1396a
nickkolok/chas-ege pull request #1453
Opened 2024-03-01 15:30 UTC by Kalendar2

2024-03-01 15:53 UTC, Kalendar2 commented
Программа сама убирает "лишние" скобки.

2024-03-01 15:58 UTC, nickkolok commented on zdn/matege2024b/16/1396.js
> +		let a = sl(1.1, 1.9, 0.1) * sl(1, 5);
А что символизирует эта конструкция?

2024-03-01 16:19 UTC, nickkolok requested changes

2024-03-01 16:19 UTC, nickkolok commented on zdn/matege2024b/16/1396.js
> +		var znak = (v ? 1 : (-1));
Если `v` дальше не используется, то можно `let znak = (1).pm()`. Кстати, смешивать `var` и `let` в одном шаблоне не рекомендуется.

2024-03-01 16:28 UTC, nickkolok commented
А с пропашими скобками бы разберёмся централизованно и системно. Если ещё где заметите - сообщайте!

2024-03-05 16:31 UTC, Kalendar2 commented
https://github.com/nickkolok/chas-ege/pull/1465

2024-03-05 16:31 UTC, closed without merging