Newtask deriv 1397d
nickkolok/chas-ege pull request #1455
Opened 2024-03-01 16:16 UTC by Kalendar2

2024-03-01 16:17 UTC, Kalendar2 commented
Не удаётся сделать скобки как в примере

2024-03-01 16:50 UTC, nickkolok commented on zdn/matege2024b/16/1397.js
> +			expr: 'divideColon(' + sl(0.01, 0.1, 0.09) + '^' + sl(2, 6) + '*10^' + sl(2, 6) + ',' + sl(2, 9) + '^' + sl(-1, -5) + ')',
> `sl(0.01, 0.1, 0.09)`
Остроумно! Но можно просто `[0.1, 0.01].iz()` Будет более читаемо и понятно.

2024-03-01 16:51 UTC, nickkolok requested changes

2024-03-01 16:51 UTC, nickkolok commented on zdn/matege2024b/16/main.js
> +	1397,
Но... здесь же должны быть не номера issue, а номера по каталогу РешуЕГЭ...

2024-03-07 16:03 UTC, nickkolok commented
Ждём #1454 , потом переставляем скобки :)

2024-03-12 17:12 UTC, nickkolok commented
Можно приступать к кореектировке!

2024-03-27 23:00 UTC, nickkolok requested changes

2024-03-27 23:00 UTC, nickkolok commented on zdn/matege2024b/16/509707.js
> +				9) + '^' + sl(-1, -5) + ')',
Снова то же замечание. Не нужно рвать строку вот так! Даже если это предлагает кнопка "Сделать красиво". Строку нужно разрывать хоть сколь-либо осмысленно. Например, можно было начать новую с `'divideColon(10^`

2024-03-29 18:26 UTC, merged