Текстовая задача №93 (99594 РешуЕГЭ) [close #1517]
nickkolok/chas-ege pull request #1524
Opened 2024-03-27 17:00 UTC by Aisse-258

![изображение](https://github.com/nickkolok/chas-ege/assets/50519492/4612cba4-68f4-47ac-ae7f-2e84558eee41)
![изображение](https://github.com/nickkolok/chas-ege/assets/50519492/3c83863d-72f3-4fe4-8195-bff1115f4d43)
![изображение](https://github.com/nickkolok/chas-ege/assets/50519492/82680a1b-ab90-44a6-93bf-c795c18c4890)

2024-03-27 18:21 UTC, nickkolok requested changes

2024-03-27 18:21 UTC, nickkolok commented on zdn/matege2024p/10/99594.js
> +	genAssertZ1000(v,'');
Всё-таки не рекомендуется оставлять сообщение об ошибке пустым. Ведь именно его будет в случае чего выводить оболочка отладки.

2024-03-27 18:24 UTC, nickkolok commented
"догнал мотоциклист"

![image](https://github.com/nickkolok/chas-ege/assets/5008131/b6f8d6c1-0cf8-4f4c-bd9f-566834790693)

2024-06-21 14:26 UTC, SugarHedgehog approved these changes
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/dc9c6600-3c96-480d-abdd-0e5397148c5c)
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/4052cbc7-4776-417d-acf4-f14786656d84)
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/471d0d6d-cc42-429b-a636-6278f13fe4e5)

2024-06-21 14:26 UTC, merged