99585
nickkolok/chas-ege pull request #1533
Opened 2024-04-03 16:44 UTC by Kalendar2

https://github.com/nickkolok/chas-ege/pull/1073

2024-04-08 23:23 UTC, nickkolok requested changes

2024-04-08 23:23 UTC, nickkolok commented on zdn/matege2023p/9/99585.js
> +		function summa(n) {
Зачем для этого отдельную функцию? Так бы и вызывали прямо в коде)

2024-04-08 23:23 UTC, nickkolok commented on zdn/matege2023p/9/99585.js
> +				'. Ежедневно она подписывает на одно и то же количество открыток больше по сравнению с предыдущим днем. ' +
А почему у нас не варьируется "открытка"? Валентинка, приглашение, распоряжение, письмо, поздравление, ценник, в конце концов!

2024-04-08 23:23 UTC, nickkolok commented on zdn/matege2023p/9/99585.js
> +				'Известно, что за первый день ' + arr + ' подписала ' + chislitlx(a, 'открытка', 'v') + '. ' +
А можем ли мы извернуться и рандомно менять местами фразы  "за первый день ... подписала ..." и "вся работа была выполнена ..."? Думаю, можем!

2024-05-26 21:21 UTC, nickkolok commented on zdn/matege2023p/9/99585.js
> +		let l2 = (l1 + 1) % 2;
`1-l1` не проще ли?..

2024-05-26 21:21 UTC, nickkolok commented on zdn/matege2023p/9/99585.js
> +		let arr2 = ['открытка', 'валентинка', 'приглашение', 'распоряжение', 'письмо', 'поздравление', 'ценник', 'книга',
Здесь разрыв строки совершенно контринтуитивный

2024-05-26 21:22 UTC, nickkolok commented on zdn/matege2023p/9/99585.js
> +		let arr3 = ['за первый день ' + arr + ' подписала ' + chislitlx(a, 'открытка', 'v'),
А если выпала не открытка, а, например, ценник?

2024-05-26 21:23 UTC, nickkolok requested changes

2024-05-26 21:23 UTC, nickkolok commented on zdn/matege2023p/9/99585.js
> -//Сергей Алендарь
Зачем же подпись-то убирать? И автор, и номер пусть стоят.

2024-06-07 15:06 UTC, SugarHedgehog reviewed
https://github.com/nickkolok/chas-ege/blob/devel/zdn/mat2014/B14/16.js
Вас опередили
3 года назад

2024-06-07 16:12 UTC, nickkolok commented
Это рефакторинг, открываем обратно.

2024-06-07 16:21 UTC, SugarHedgehog commented
Не вводите проверяющего в заблуждение!
Если это рефакторинг, то он ДОЛЖЕН заменять существующий файл, а не создавать новый

2024-06-14 00:14 UTC, nickkolok commented
@SugarHedgehog А если по существу, без учёта существующих файлов?

2024-06-14 08:35 UTC, SugarHedgehog commented
>по существу

Шаблон стал в разы менее разнообразным на вопросы и формулировки
По-моему мнению, шаблон при рефакторинге либо должен сохранить свою вариативность, либо приумножить её

2024-06-14 16:38 UTC, nickkolok commented
Зато более пофипишным, не правда ли?

2024-06-14 16:38 UTC, nickkolok commented
Поэтому мы старый и оставляем.

2024-06-17 10:17 UTC, merged