drawEllipse
nickkolok/chas-ege pull request #1563
Opened 2024-04-17 08:11 UTC by SugarHedgehog

2024-04-17 20:20 UTC, nickkolok commented
Предлагаю параметры `rotation, startAngle, endAngle,` также сделать опциональными.

2024-04-18 18:17 UTC, SugarHedgehog commented
> Предлагаю параметры `rotation, startAngle, endAngle,` также сделать опциональными.

Возражаю
Это нарушает каноничность исходной функции

2025-02-04 13:20 UTC, nickkolok commented
Последний у исходной функции и так опционален:
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/ellipse
А вот три угла, которые в 90% будут указываться после гугления на стандартные значения, стОит сразу делать опциональными. Чтобы для рисования обычного ровненького лежачего эллипса не надо было долго и мучительно гуглить!

2025-02-06 20:44 UTC, nickkolok requested changes
И вроде всё.

2025-02-06 20:44 UTC, nickkolok commented on lib/canvas.js
А чего это теперь отступы не табами, как во всём файле, а пробелами? Ой как не хватает eslint в CI...

2025-02-10 21:36 UTC, merged