Newtask 26717a
nickkolok/chas-ege pull request #1605
Opened 2024-06-16 21:34 UTC by Kalendar2

2024-06-16 21:50 UTC, Kalendar2 commented
https://github.com/nickkolok/chas-ege/issues/1482

2024-06-16 21:54 UTC, nickkolok commented
`primaryStep` поставил в `0.01`, иначе висло наглухо. Возражения?
![image](https://github.com/nickkolok/chas-ege/assets/5008131/cf4867b5-6839-49df-a079-e00b5d478862)

А вот здесь, кажется, перед константой потерян знак "плюс" или "минус".

![image](https://github.com/nickkolok/chas-ege/assets/5008131/36b15dba-73e9-42ff-acb9-c38766e55c6f)

2024-06-17 16:09 UTC, nickkolok commented
Левый конец отрезка очень часто получается отрицательным. Причём часто эту отрицательность не могут компенсировать слагаемые при иксе, под логарифмом получается отрицтальное значение, и шаблон уходит на перегенерацию. Не надо так!

2024-06-17 20:36 UTC, nickkolok commented
Всё гораздо проще и сложнее одновременно. Коэффициент, обозначенный за $a$, ставится перед иксом и (перед логарифмом или в степени у скобки подлогарифменного выражения).

2024-06-17 21:33 UTC, nickkolok commented on zdn/matege2023p/9/26717.js
> +		let c = a;
А если всегда $c=a$, то зачем нам две одинаковые переменные?

2024-06-17 21:34 UTC, nickkolok commented on zdn/matege2023p/9/26717.js
> +		if (d == 0) {
Если `d` нигде далее по коду не используется, то лаконичнее делать `if (sl1())`

2024-06-17 21:35 UTC, nickkolok commented on zdn/matege2023p/9/26717.js
> +		let k = sl(0, 10).pm();
А в чём смысл этой конструкции? Я понимаю, `sl(1,9).pm()` - это чтобы нуля избежать. Но тут-то почему не `sl(-10,10)` ?

2024-06-17 21:35 UTC, nickkolok commented on zdn/matege2023p/9/26717.js
> +			expr: arr1[maxmin]+a + 'log(x+' + b + ')^' + g + '+'+arr2[maxmin] + c + 'x+' + k,
`arr1[1-maxmin]`

2024-06-17 21:36 UTC, nickkolok commented on zdn/matege2023p/9/26717.js
> +			expr: arr1[maxmin]+a + 'log(x+' + b + ')^' + g + '+'+arr2[maxmin] + c + 'x+' + k,
А ещё есть такая фишка:
`arr1.shuffle()`
И потом просто `arr1[0]` и `arr1[1]`

2024-06-17 22:04 UTC, nickkolok commented on zdn/matege2023p/9/26717.js
> +		g = a;
А отступ?

2024-06-17 22:05 UTC, nickkolok requested changes

2024-06-17 22:05 UTC, nickkolok commented on zdn/matege2023p/9/26717.js
> +		let g = 1;
Единички в степени быть не должно. Может, `g=''`? Будет работать?
![image](https://github.com/nickkolok/chas-ege/assets/5008131/4eefe855-7a9b-4ab4-a928-33a0b4979b2e)

2024-06-17 22:31 UTC, merged