Девятка о грустном мосте
nickkolok/chas-ege pull request #1654
Opened 2024-07-11 12:16 UTC by mcFrene

https://github.com/nickkolok/chas-ege/issues/1367

2024-07-11 18:35 UTC, nickkolok commented on zdn/matege2024p/9/324467.js
> +	let url = URL.createObjectURL(svgBlob);
Косяк с отступами

2024-07-11 18:36 UTC, nickkolok requested changes
А остальное вроде ОК

2024-07-11 18:36 UTC, nickkolok commented on zdn/matege2024p/9/324467.js
> +         URL.revokeObjectURL(url);
И тут

2024-07-11 18:52 UTC, mcFrene commented
![scr1](https://github.com/nickkolok/chas-ege/assets/149618826/d20a3a68-cbe0-42d2-a1ff-da59db3d5115)

Откуда вообще эти косяки с отступами вылезли..

2024-07-11 20:57 UTC, nickkolok commented on zdn/matege2024p/9/324467.js
> +			   style="font-variant:normal;font-weight:normal;font-size:11.5px;font-family:'Times New Roman';-inkscape-font-specification:TimesNewRomanPSMT;writing-mode:lr-tb;fill:#040606;fill-opacity:1;fill-r
Отступы вроде ок.
Я, конечно, понимаю, что это загон, но... `Times New Roman` - это буквально символ проприетарного стандарта. Не тащит ли ЧАС-ЕГЭ с собой свободные шрифты? И нельзя ли его тут заменить?.. Liberation Serif, кажется.

2024-07-11 22:09 UTC, mcFrene commented on zdn/matege2024p/9/324467.js
> +			   style="font-variant:normal;font-weight:normal;font-size:11.5px;font-family:'Times New Roman';-inkscape-font-specification:TimesNewRomanPSMT;writing-mode:lr-tb;fill:#040606;fill-opacity:1;fill-r
Не уверен, что что-то изменилось, но везде где можно названия я поменял

2024-07-13 12:51 UTC, SugarHedgehog reviewed
![изображение](https://github.com/user-attachments/assets/9a60a027-4ede-4e29-8ded-c5875adeb4c3)
Новая единица иземерения Етры
![изображение](https://github.com/user-attachments/assets/ce4fdf5f-d6f0-47dc-b649-3b70da0a3096)
![изображение](https://github.com/user-attachments/assets/47edea1d-c42f-4025-ac97-ac7afda062ff)
Но считает верно

2024-07-13 14:18 UTC, SugarHedgehog approved these changes

2024-07-14 16:47 UTC, merged