Newtask 320211
nickkolok/chas-ege pull request #846
Opened 2022-02-20 18:52 UTC by warekeruz

2023-08-02 21:26 UTC, nickkolok requested changes

2023-08-02 21:26 UTC, nickkolok commented on zdn/mat2014/B6/320211.js
> +//РАБОТАЕТ
Это довольно-таки... громкий комментарий. В шаблоне, который окажется в основной ветке, он не нужен. Там и так предполагается, что всё работает.

2023-08-02 21:26 UTC, nickkolok commented on zdn/mat2014/B6/320211.js
> +    else answers = 1 - (verneispr * verzabrakneispr + ((1 - verneispr) * verzabrispr))
Скобочки и перенос на новую строку

2023-08-02 21:26 UTC, nickkolok commented on zdn/mat2014/B6/320211.js
> +
Пустая строка не нужна. Условие тут такое, что лучше его разбить на строка = предложение.

2023-08-02 21:26 UTC, nickkolok commented on zdn/mat2014/B6/320211.js
> +    var verneispr = (sluchch(1, 15)) / 100;
Это немножечко варварство - при возможности указать шаг третьим параметром

2023-08-02 21:26 UTC, nickkolok commented on zdn/mat2014/B6/320211.js
> +        text: 'Автоматическая линия изготавливает ' + predm.im + '. Вероятность того, что готовая ' +
Конвейер, фабрика, завод, мастерская, цех, <s>китайское подполье</s>

2023-08-02 21:26 UTC, nickkolok commented on zdn/mat2014/B6/320211.js
> +            '' + predm.ie + ' неисправна, равна ' + verneispr + '. Перед упаковкой каждая ' + predm.ie + ' проходит систему' +
Варьировать: либо давать вероятность неисправности, либо давать вероятность исправности. Или так нельзя, недостаточно ФИПИшно?

2023-08-02 21:26 UTC, nickkolok commented on zdn/mat2014/B6/320211.js
> +            'Вероятность того, что система по ошибке забракует исправную ' + predm.ve + ', равна ' + verzabrispr + '. ' +
Эти два предложения можно случайно менять местами
`[,].shuffle().join(' ')`

2024-11-29 07:28 UTC, SugarHedgehog commented
Решает верно

2024-11-30 11:16 UTC, merged