NewTask_500246
nickkolok/chas-ege pull request #995
Opened 2023-02-14 20:05 UTC by SugarHedgehog

2023-09-08 21:07 UTC, nickkolok requested changes

2023-09-08 21:07 UTC, nickkolok commented on zdn/matege2023p/1/500246.js
> +		while (letter.length != 4) {
чтототам.iz(4);

Но вообще - если здесь нет иллюстрации - то это тот самый случай, когда `variativeABC()` делает код сильно более коротким и читаемым.

2023-09-18 16:18 UTC, SugarHedgehog commented
Спрашивается
почему нет рисунка!
Это безобразие

2023-09-18 16:52 UTC, SugarHedgehog commented
Зависит от #1202

2024-02-12 22:37 UTC, nickkolok requested changes

2024-02-12 22:37 UTC, nickkolok commented on zdn/matege2023p/1/500246.js
> +				'Найдите угол $' + letter[1] + letter[3] + letter[2] + '$. Ответ дайте в градусах.',
Вот где, например, `.rndReverse()` пригодится!

2024-02-12 22:37 UTC, nickkolok commented
Таки оно иногда слегка обрезано.
![image](https://github.com/nickkolok/chas-ege/assets/5008131/2c879c3f-7f88-4c06-8d96-c9ac54411167)

Но считает правильно!

2024-02-13 14:32 UTC, nickkolok commented
Ждём #1390

2024-02-18 15:58 UTC, nickkolok commented
А обратная задача?

2024-02-18 16:36 UTC, nickkolok commented
Пробел перед "Найдите"
![image](https://github.com/nickkolok/chas-ege/assets/5008131/58cd8602-018e-40fb-b99e-e1e2b29feb50)

2024-02-20 17:23 UTC, merged